version: '3.8'

services:
  mysql:
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 1s
    image: mariadb:10.5
    ports:
      - "3306:3306"
    restart: "always"

  openmrs:
    depends_on:
      - mysql
    environment:
      DB_AUTO_UPDATE: 'true'
      DB_CREATE_TABLES: 'true'
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: mysql
      DB_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
      DB_USERNAME: ${MYSQL_USER:-openmrs}
      MODULE_WEB_ADMIN: 'false'
    healthcheck:
      test: curl-f http://localhost:8080/openmrs
      timeout: 20s
    image: openmrs/openmrs-distro-platform:2.3.3
    ports:
      - "8080:8080"
    restart: "always"

  proxy:
    build:
      args:
        TIMEZONE: "${TIMEZONE}"
      context: proxy/
    command: "httpd-foreground ${PROXY_TLS}"
    healthcheck:
      test: curl -f http://localhost
      timeout: 20s
    networks:
      bahmni:
        aliases:
          - bahmni-proxy
          - proxy
    ports:
      - "${PROXY_PUBLIC_PORT:-80}:80"
      - "${PROXY_PUBLIC_PORT_TLS:-443}:443"
    volumes:
      - "./proxy/confs:/usr/local/apache2/conf/extra"
      - "${PROXY_TLS_CERTS_PATH:-proxy-tls-certs}:/etc/tls"

networks:
  bahmni:

volumes:
  proxy-tls-certs:
